#!/usr/bin/env bash
# Regenerate docker/nginx/snippets/cloudflare-real-ip.conf from Cloudflare's published IP lists.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="nginx/snippets/cloudflare-real-ip.conf"

{
  echo "# Trust Cloudflare proxy IPs and restore the real client address."
  echo "# Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6"
  echo "# Regenerated by ./scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d)"
  echo ""
  echo "# IPv4"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done < <(curl -fsSL https://www.cloudflare.com/ips-v4)
  echo ""
  echo "# IPv6"
  while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done < <(curl -fsSL https://www.cloudflare.com/ips-v6)
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$OUT"

echo "Wrote $OUT"
echo "Reload nginx after deploy: docker compose exec nginx nginx -s reload"
